//
// Generated file, do not edit! Created by opp_msgtool 6.0 from RouteRequest.msg.
//

#ifndef __ROUTEREQUEST_M_H
#define __ROUTEREQUEST_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class RouteRequest;
/**
 * Class generated from <tt>RouteRequest.msg:15</tt> by opp_msgtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * packet RouteRequest
 * {
 *     int sourceUEID;
 *     int destinationUEID;
 *     // Add other necessary fields
 * }
 * </pre>
 */
class RouteRequest : public ::omnetpp::cPacket
{
  protected:
    int sourceUEID = 0;
    int destinationUEID = 0;

  private:
    void copy(const RouteRequest& other);

  protected:
    bool operator==(const RouteRequest&) = delete;

  public:
    RouteRequest(const char *name=nullptr, short kind=0);
    RouteRequest(const RouteRequest& other);
    virtual ~RouteRequest();
    RouteRequest& operator=(const RouteRequest& other);
    virtual RouteRequest *dup() const override {return new RouteRequest(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSourceUEID() const;
    virtual void setSourceUEID(int sourceUEID);

    virtual int getDestinationUEID() const;
    virtual void setDestinationUEID(int destinationUEID);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RouteRequest& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RouteRequest& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline RouteRequest *fromAnyPtr(any_ptr ptr) { return check_and_cast<RouteRequest*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __ROUTEREQUEST_M_H

